### PR TITLE
Fixing 2 bugs and adding new example scripts to test the installation.

### PR DESCRIPTION
**Pull request by Masaaki-75**
Two bugs are fixed.
- Incontiguous gradient error:
  - Located at `src/python/torch_radon/differentiable_functions.py`.
  - The gradient for deep learning backpropagation is incontiguous. This can be reproduced using the test script `examples/radon_v2_example3.py`, and is fixed by simply adding `grad_x = grad_x.contiguous()`.
- Numpy assertion error : 
  - Located at `src/python/torch_radon/filtering.py`. 
  - `np.int` in higher numpy version will cause `AttributeError: module 'numpy' has no attribute 'int'`. This was fixed by simply replacing `np.int` with `int`.

New scripts are added for fully checking the installation. The previous scripts in `examples` are not enough to test whether the package is installed correctly.

### CODE REVIEW

**Comment by carterbox** [comment]
Thank you for bringing these fixes. However, this is a lot of code to review all at once. Could you please break these changes into three independent pull requests focusing on the following topics:

1. noncontiguous inputs patch 
2. numpy deprecation of numpy.int patch #12
3. new installation checking scripts

Thanks!

**Comment by carterbox** [comment]
Let's do numpy first because that one is easy!

**Comment by Masaaki-75** [comment]
OK! I will open new PR for each :) Should I close this one?

**Comment by carterbox** [comment]
Closing because this was replaced by #12 and #13

**Pull request closed without merging**
